### ISSUE TITLE
Running on Self Hosted Runner

### ISSUE THREAD

**Issue by dvargasfuertes** [chrislennon/action-aws-cli#4]
Hey 👋 

I was using your github action here: (https://github.com/dvargas92495/moonlight/blob/master/.github/workflows/qa_deploy.yml#L28)

I found that it worked great with the standard github action runner. When I switched over to a self hosted runner, it works on the first run, but on the second runner I get `aws not found` on subsequent commands. I'm working around this for now by adding a step before it that `rm -Rf /opt/hostedtoolcache/aws`, so that we fresh install the aws cli on every run. Obviously this is not ideal as it adds a minute of run time on every run. For context, my self hosted runner is an Ubuntu 18.04 ec2 instance on AWS.

Is this repo still actively maintained? Have you seen this issue before? If not, could I try to see if I could fix it and contribute to the repo?

**Comment by chrislennon** [comment]
Hey @dvargas92495 - thanks for reaching out!

Let me give you what context I can on this project then can attempt to debug your issue.

This action was created early in the Actions V2 ecosystem and I believe it has evolved significantly since then:
- self hosted runners didn't exist - so I've done no testing with them
- the AWS CLI wasn't pre installed on many base images but it should be now - the list is available [here](https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners)
- Whilst this project isn't active (as in I'm not using it daily in my own projects) - I try not to abandon projects, though I was kind of under the assumption GitHub had fixed this with the base images.


With regards to your issue, I am trying to review your action runs - would be helpful if you could post the 'working' first run and the failed second one. Would give me some targeted logs to check.
- My first gut feeling would be that perhaps its as simple as (on the second run) AWS CLI isn't found in the image's PATH, thus hard removing it and reinstalling it could fix this - [this line](https://github.com/chrislennon/action-aws-cli/blob/master/src/main.ts#L37) (I think) would be the one that adds it to the path.
  - That said unless you are explicitly skipping my action when AWS CLI is believed to be installed I believe I attempt reinstall again anyway [here](https://github.com/chrislennon/action-aws-cli/blob/master/src/main.ts#L16)
- You have other routes to fixing this I think, not just with my action (not that I wont help further ofc 😄 ):
  - Use of the preinstalled AWS CLI on the base image - will still need to drop in your secrets
  - Perhaps crafting your own image in a separate repository and then consuming that in your project could give you a level of abstraction and speed up each run. e.g. publish a docker image to GitHub packages in `repoX` then in your `moonlight` repo refer to that image. This would mean all your tooling AWS, terraform etc is already available to you and you could increment developments on `repoX` independently.

I will dig into this outside of office my working hours but thought some initial thoughts could help move you in a direction.

Please report back if you find anything out! Thanks for raising this new issue!

@ThomasShaped - perhaps this is something you would have some thoughts on too?

**Comment by otter-computer** [comment]
Hey, yep to pretty much everything above! This action was created during the time the AWS CLI wasn't pre installed on GitHub-hosted runners. This now not the case so this Action shouldn't be used anymore.

If you want to use the CLI on a self-hosted runner then I'd recommend installing the CLI on whatever machine/image you use and write the commands directly in the `run` section of your actions steps. Either that or use the [official AWS Actions](https://github.com/AWS-actions) if they suit your needs.

**Comment by dvargasfuertes** [comment]
Thanks for the responses! I think I'm going to move towards just having the cli installed on the ec2 image directly and removing the action
